class Constants:


    # CONFIGURATIONID              = "configurationId"
    # APP                          = "app"
    # APPINTEGRATIONID             = "appIntegrationId"
    # MANAGEMENTPROFILEID          = "managementProfileId"
    # MESSAGEID                    = "messageId"
    # APPNAME                      = "appName"
    PAYLOAD                      = "payload"
    NATIVE_TYPE                  = "nativeType"
    RESOURCETYPE                 = "resourceType"
    RESOURCETYPES                = "resourceTypes"
    #
    #
    # CURRENT_RESOURCESET          = "currentResourceSet"
    # CURRENT_RELATIONSHIPSET      = "currentRelationshipSet"
    MONITOR_ID                    = "monitorId"
    # TEMPLATESHAVALUE             = "templateShaValue"
    # APPCONFIG                    = "appConfig"
    # APPCONFIGID                  = "appConfigId"
    # APPCONFIGSHAVAL              = "appConfigShaValue"
    #
    CREDENTIALS                  = "credentials"
    CREDENTIAL                   = "credential"
    FIELDNAME                    = "fieldName"
    CREDENTIALVALUE              = "credentialValue"
    CIPHER                       = "cipher"
    #
    DATA                         = "data"
    RESOURCES                    = "resources"
    RESOURCE_ID                   = "resourceId"
    # RESOURCESHAVALUE             = "resourceShaValue"
    # MONITORS                     = "monitors"
    # UUID                         = "uuid"
    METRICS                      = "metrics"
    # CONFIGURATIONNAME            = "configurationName"
    # ROOT_RESOURCE_TAGS           = "RootResourceTags"
    #
    MEMBER_OF                    = "memberof"
    # DEPENDENDS_ON                = "dependsOn"
    COMPONENT_OF                 = "componentOf"
    # CONNECTED_TO                 = "connectedTo"
    #
    TEMPLATE_ID                   = "templateId"
    # TEMPLATE                     = "template"
    # CONFIGID                     = "configId"
    # SUBJECT                        = "subject"
    # ALERT_UUID                    = "uuId"
    # DESCRIPTION                = "description"
    # IS_RESOLVED                    = " is Resolved"
    MOID                         = "moId"
    SOURCE_MOID                  = "sourceId"
    TARGET_MOID                  = "targetId"
    # RESOURCEUUID                 = "resourceUUID"
    #
    # HTTPS                        = "https"
    # HTTP                            = "http"
    IPADDRESS                   =  "ipAddress"
    MANAGER_IP_ADDRESS = "dellFlexManagerIP"
    PROTOCOL                    = "isSecure"
    USERNAME                        = "username"
    PASSWORD                        = "password"
    MANAGER_USERNAME = "managerUsername"
    MANAGER_PASSWORD = "managerPassword"
    #
    ID                            = "id"
    NAME                            = "name"
    TYPE                            = "type"
    SYSTEM_VERSION_NAME            = "systemVersionName"
    SW_ID                           = "swid"
    PROTECTION_DOMAIN_ID            = "protectionDomainId"
    SYSTEM_ID                    = "systemId"
    SDC_IP                        = "sdcIp"
    VERSION_INFO                    = "versionInfo"
    OS_TYPE                        = "osType"
    OS                             = "os"
    MANAGED_DEVICE_OS = "operatingSystem"
    TAGS                           = "tags"
    SOFT_VERSION_INFO            = "softwareVersionInfo"
    STORAGEPOOL_ID                = "storagePoolId"
    # FIRMWARE_VERSION                = "firmwareVersion"
    SERIAL_NUMBER                  = "serialNumber"
    MODEL_NAME                    = "modelName"

    MANUFACTURER = "manufacturer"
    MAKE = "make"

    MODEL                          = "model"
    RESOURCE_NAME                  ="resourceName"
    HOST_NAME                      = "hostName"
    MDM_CLUSTER                    = "mdmCluster"
    MASTER                         = "master"
    MANAGEMENT_IP                = "managementIPs"
    PORT                            = "port"
    # TYPE                            = "Type"
    SDC_TYPE                        = "sdcType"
    SIZE                        = "sizeInKb"
    SIZE_IN_KB                        = "Size In Kb"
    VOLUMETYPE                     = "volumeType"
    VOLUME_TYPE                    = "Volume Type"
    # VERSION                        = "Version"
    DEVICETYPE                    = "deviceType"

    DEVICE_TYPE                    = "Device Type"
    SERVICETAG = "serviceTag"
    SERVICE_TAG = "Service Tag"
    MEDIA_TYPE                    = "Media Type"
    MEDIATYPE                      = "mediaType"

    VENDORNAME                    = "vendorName"
    VENDOR_NAME                    = "Vendor Name"
    HYPHEN                        = "-"
    REF_ID = "refId"
    EMPTY_STRING = ""
    DISPLAY_NAME = "displayName"
    MANAGED = "MANAGED"
    READY = "READY"
    GREEN = "GREEN"
    COMPLIANT = "COMPLIANT"

    SWITCH_STATE_METRIC = "dell_powerflex_switch_State"
    SWITCH_MANAGED_STATE_METRIC = "dell_powerflex_switch_ManagedState"
    SWITCH_COMPLIANCE_METRIC = "dell_powerflex_switch_Compliance"


    VCENTER_STATE_METRIC = "dell_powerflex_vcenter_State"
    VCENTER_MANAGED_STATE_METRIC = "dell_powerflex_vcenter_ManagedState"
    VCENTER_COMPLIANCE_METRIC = "dell_powerflex_vcenter_Compliance"


    ROOT_MOID = "Root_Moid"
    # # native types
    SYSTEM                        = "System"
    MDM                           = "Mdm"
    SDC                            = "Sdc"
    PROTECTION_DOMAIN            = "ProtectionDomain"
    STORAGE_POOL                    = "StoragePool"
    SDS                            = "Sds"
    VOLUME                        = "Volume"
    # VTREE                        = "VTree"
    DEVICE                        = "Device"
    # SPSDS                        = "SpSds"
    MANAGED_SERVER                 = "MangedServer"
    MANAGED_SWITCH = "MangedSwitch"
    MANAGED_VCENTER = "MangedSwitch"
    SERVER = "server"
    SWITCH = "switch"
    VCENTER = "vcenter"


    STATISTICS                       ="Statistics"
    METRIC_NAME                     ="metricName"
    INSTANCE_VALUE                  ="instanceVal"
    TIME_STAMP                      ="ts"

    START_PATTERN                     ="$."
    MDM_PATTERN                        = "$.mdmCluster."
    HAS_RELATION                    ="hasRelationship"


    SERVER_STATE_METRIC = "dell_powerflex_server_State"
    SERVER_MANAGED_STATE_METRIC = "dell_powerflex_server_ManagedState"
    SERVER_COMPLIANCE_METRIC = "dell_powerflex_server_Compliance"

    TRUE = "true"
    FALSE = "false"

    # JSON                            = ".json"
    # STATISTICS_JSON                = "_Statistics.json"
    # INSTANCE_JSON                = "_Instance.json"
    #

    MANAGER_NATIVE_TYPE = "Dell PowerFlex Manager"
    SERVER_NATIVE_TYPE = "Dell PowerFlex Manager Server"
    SWITCH_NATIVE_TYPE = "Dell PowerFlex Manager Switch"
    VCENTER_NATIVE_TYPE = "Dell PowerFlex Manager VCenter"
    SYSTEM_NATIVE_TYPE            = "Dell PowerFlex Gateway"
    MDM_NATIVE_TYPE                = "Dell PowerFlex MDM Cluster"
    SDC_NATIVE_TYPE                = "Dell PowerFlex SDC"
    PROTECTION_DOMAIN_NATIVE_TYPE= "Dell PowerFlex Protection Domain"
    STORAGE_POOL_NATIVE_TYPE        = "Dell PowerFlex Storage Pool"
    SDS_NATIVE_TYPE                = "Dell PowerFlex SDS"
    VOLUME_NATIVE_TYPE            = "Dell PowerFlex Volume"
    VTREE_NATIVE_TYPE            = "Dell PowerFlex VTree"
    DEVICE_NATIVE_TYPE            = "Dell PowerFlex Device"
    MANAGER_NATIVE_TYPE = "Dell PowerFlex Manager"
    # SPSDS_NATIVE_TYPE            = "Dell PowerFlex SpSds"
    #
    UNUSED_CAPACITY                = "unusedCapacityInKb"
    # REBALANCE_CAPACITY            = "rebalanceCapacityInKb"
    # SNAP_CAPACITY                = "snapCapacityInUseInKb"
    # USER_DATA_CAPACITY            = "maxUserDataCapacityInKb"
    # THICK_CAPACITY                = "thickCapacityInUseInKb"
    # THIN_CAPACITY                = "thinCapacityInUseInKb"
    MAX_CAPACITY                    = "maxCapacityInKb"
    # CLUSTER_STATE                = "clusterState"
    CLUSTER_NORMAL                = "ClusteredNormal"
    # DEVICE_STATE                    = "deviceState"
    NORMAL                        = "Normal"
    CONNECTED                    = "Connected"
    # SDS_STATE                    = "sdsState"
    MDM_CONNECTION_STATE            = "mdmConnectionState"
    # PROTECTION_DOMAIN_STATE        = "protectionDomainState"
    ACTIVE                        = "Active"
    # CAPACITY_USAGE_STATE            = "capacityUsageState"
    #
    STOREAGE_POOL_STATE                             = "dell_powerflex_storagePool_UsageState"

    SYSTEM_TOTAL_USED_CAPACITY                     = "dell_powerflex_gateway_TotalUsedCapacity"

    SYSTEM_CAPACITY_UTILIZATION                   = "dell_powerflex_gateway_CapacityUtilization"
    #
    MDM_CLUSTER_STATE_METRIC                         = "dell_powerflex_mdm_CurrentState"
    SDS_STATE_METRIC                                 = "dell_powerflex_sds_ConnectionState"
    SDC_STATE_METRIC                                 = "dell_powerflex_sdc_ConnectionState"
    PROTECTION_DOMAIN_STATE_METRIC                 = "dell_powerflex_protectionDomain_State"
    DEVICE_STATE_METRIC                         = "dell_powerflex_device_State"

    


    
    MANAGED_DEVICE = "/Api/V1/ManagedDevice"

