{{- with $.Values.autoScaling }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sdkApp.name" $}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sdkApp.name" $}}
  minReplicas: {{ .min }}
  maxReplicas: {{ .max }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 60
      selectPolicy: Min
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30 
  metrics:
    - type: Resource
      resource:
        name: memory 
        target:
          type: Utilization 
          averageUtilization: {{ .utilization.memory }}
{{- end }}
