apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sdkApp.name" $ }}-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ include "sdkApp.name" $ }}
